Core_PrestitiVideoteca/Core_PrestitiVideoteca/Models/Film.cs
using System;
using System.Collections.Generic;

namespace Core_PrestitiVideoteca.Models
{
    public partial class Film
    {
        public Film()
        {
            Prestiti = new HashSet<Prestito>();
        }

        public int Codice { get; set; }
        public string? Titolo { get; set; }
        public string? Supporto { get; set; }
        public string? Regista { get; set; }
        public string? Attori { get; set; }
        public string? Genere { get; set; }

        public virtual ICollection<Prestito> Prestiti { get; set; }
    }
}

Core_PrestitiVideoteca/Core_PrestitiVideoteca/Controllers/FilmsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Core_PrestitiVideoteca.Models;

namespace Core_PrestitiVideoteca.Controllers
{
    public class FilmsController : Controller
    {
        private readonly Core_PrestitiVideotecaContext _context;

        public FilmsController(Core_PrestitiVideotecaContext context)
        {
            _context = context;
        }

        // GET: Films
        public async Task<IActionResult> Index(int? numeroPerPagina)
        {
            var lista = _context.Films.IgnoreQueryFilters();
            if (numeroPerPagina != null)
                lista = _context.Films.Take((int)numeroPerPagina);
            return _context.Films != null ?
                          View(await _context.Films.ToListAsync()) :
                          Problem("Entity set 'Core_PrestitiVideotecaContext.Films'  is null.");
        }

        // GET: Films/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Films == null)
            {
                return NotFound();
            }

            var film = await _context.Films
                .FirstOrDefaultAsync(m => m.Codice == id);
            if (film == null)
            {
                return NotFound();
            }

            return View(film);
        }

        // GET: Films/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Films/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Codice,Titolo,Supporto,Regista,Attori,Genere")] Film film)
        {
            if (ModelState.IsValid)
            {
                _context.Add(film);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(film);
        }

        // GET: Films/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Films == null)
            {
                return NotFound();
            }

            var film = await _context.Films.FindAsync(id);
            if (film == null)
            {
                return NotFound();
            }
            return View(film);
        }

        // POST: Films/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Codice,Titolo,Supporto,Regista,Attori,Genere")] Film film)
        {
            if (id != film.Codice)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(film);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FilmExists(film.Codice))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(film);
        }

        // GET: Films/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Films == null)
            {
                return NotFound();
            }

            var film = await _context.Films
                .FirstOrDefaultAsync(m => m.Codice == id);
            if (film == null)
            {
                return NotFound();
            }

            return View(film);
        }

        // POST: Films/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Films == null)
            {
                return Problem("Entity set 'Core_PrestitiVideotecaContext.Films'  is null.");
            }
            var film = await _context.Films.FindAsync(id);
            if (film != null)
            {
                _context.Films.Remove(film);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> CercaTitolo(string searchQuery)
        {
            if (string.IsNullOrWhiteSpace(searchQuery))
            {
                return RedirectToAction(nameof(Index));
            }
            var films = await _context.Films
                .Where(f => f.Titolo.Contains(searchQuery))
                .ToListAsync();
            return View("Index", films);
        }
        public async Task<IActionResult> CercaAttore(string searchQuery)
        {
            if (string.IsNullOrWhiteSpace(searchQuery))
            {
                return RedirectToAction(nameof(Index));
            }
            var films = await _context.Films
                .Where(f => f.Attori.Contains(searchQuery))
                .ToListAsync();
            return View("Index", films);
        }

        private bool FilmExists(int id)
        {
          return (_context.Films?.Any(e => e.Codice == id)).GetValueOrDefault();
        }
    }
}

Core_PrestitiVideoteca/Core_PrestitiVideoteca/Views/Films/Details.cshtml
@model Core_PrestitiVideoteca.Models.Film

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Film</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Titolo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Titolo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Supporto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Supporto)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Regista)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Regista)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Attori)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Attori)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genere)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genere)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Codice">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Core_PrestitiVideoteca/Core_PrestitiVideoteca/Views/Films/Index.cshtml
@model IEnumerable<Core_PrestitiVideoteca.Models.Film>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<form asp-controller="Films" asp-action="CercaTitolo" method="get">
    <input type="text" name="searchQuery" placeholder="Cerca per titolo" />
    <input type="submit" value="Search"/>
</form>
<form asp-controller="Films" asp-action="CercaAttore" method="get">
    <input type="text" name="searchQuery" placeholder="Cerca per attore" />
    <input type="submit" value="Search"/>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Titolo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Supporto)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Regista)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Attori)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Genere)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Titolo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Supporto)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Regista)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Attori)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Genere)
            </td>
            <td>
                <a asp-action="Details" asp-route-id="@item.Codice">Details</a> |

            </td>
        </tr>
}
    </tbody>
</table>